### ISSUE TITLE
Implement Navigation Drawer

### ISSUE THREAD

**Issue by Shailesh351** [wdlsvnit/Quick-Share#4]
**Actual Behaviour**

Navigtion drawer is not implemented 

**Expected Behaviour**

Implement Navigation Drawer containing "Profile , Home, Settings, Sign out" in MainActivity

**Comment by anandwana001** [comment]
@Shailesh351 I would like to do this.

**Comment by Shailesh351** [comment]
Sure @anandwana001 :smile:

**Comment by Shailesh351** [comment]
@anandwana001 you working on this issue?

**Comment by anandwana001** [comment]
Sorry for delay, will send PR by today

**Comment by anandwana001** [comment]
@Shailesh351 MainActivity having login button, we need to shift/make new login screen for this and then develop navigation drawer inside it!!

**Comment by Shailesh351** [comment]
Yes, shift login button to Home Fragment. 

Just create project on console and add google-services.json for now. I will add you as collaborator soom. I'm in the lecture 😅

**Comment by Shailesh351** [comment]
@anandwana001 Your email id?

**Comment by Shailesh351** [comment]
We need to speed up the project. @anandwana001 You working on this issue?

**Comment by anandwana001** [comment]
Currently, no
