### ISSUE TITLE
Get device id and save it on Firebase database

### ISSUE THREAD

**Issue by Shailesh351** [wdlsvnit/Quick-Share#5]
**Expected Behaviour**

Get unique device id and save it on firebase database so that we can identify device using it.

**Comment by anandwana001** [comment]
@Shailesh351  Does unique device id is same as what each user has a **unique id** after authentication?

**Comment by Shailesh351** [comment]
No device id will be different from uid of firebase user, We will use device id to get from which device clips are copied
